"use strict";

angular.module("WazzyPortfolio").controller("DashboardController", function($scope) {
	
	$scope.paragraph1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu ornare risus, id sollicitudin metus. Fusce quis nisi nec sem tincidunt aliquam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris eu purus sed libero scelerisque feugiat. Phasellus justo leo, sollicitudin eu sapien vitae, vestibulum rhoncus velit. Aliquam nibh dui, rhoncus sit amet faucibus venenatis, malesuada non est. In at sapien non risus laoreet cursus. Sed non justo dignissim, consectetur lacus nec, efficitur odio. Maecenas ipsum enim, fermentum non mattis id, tristique at metus. Sed non feugiat odio, vel consequat nibh. Mauris lobortis magna et erat malesuada, ac placerat arcu ullamcorper. Vivamus cursus ultrices dui id suscipit. In laoreet odio vel fermentum lacinia.";
	
	$scope.paragraph2 = "Proin id odio suscipit, sollicitudin eros vel, sodales turpis. Donec accumsan, neque eu malesuada bibendum, lorem massa ornare mi, in scelerisque odio turpis in nulla. Sed diam risus, vestibulum vel dolor ac, placerat ultrices urna. Quisque non nulla quam. Fusce ut laoreet eros. Nullam ac nisi mauris. Vivamus at lorem arcu. Fusce lacinia nulla vel nisi luctus accumsan. Quisque at ex nec arcu venenatis pulvinar. Quisque risus risus, vestibulum a nisl a, aliquet luctus arcu. Nunc facilisis dui ac eros dictum malesuada. Sed luctus mauris tortor. Duis at nulla placerat, pellentesque est in, interdum eros. Donec ullamcorper nibh est, vitae pretium arcu fringilla a. Vestibulum et sapien nec ipsum varius accumsan.";
	
	$scope.paragraph3 = "Aliquam et ex sem. Sed lacus elit, iaculis ut lectus ut, sollicitudin mattis elit. Phasellus gravida tempor nisl, non placerat felis auctor sed. Pellentesque molestie turpis vitae mollis aliquam. Pellentesque mattis dignissim turpis, nec porta sapien tincidunt eget. Aliquam pharetra massa in nisi auctor convallis. Suspendisse semper diam mauris, ut sodales leo tempus et. Nulla vitae nisl a est aliquet suscipit. Suspendisse et dignissim leo.";
	
	$scope.paragraph4 = "Maecenas finibus mi sit amet turpis posuere cursus. Nulla facilisi. Morbi sed nisi scelerisque, molestie arcu at, faucibus lorem. Sed gravida lorem id risus lacinia pellentesque. Mauris at semper lectus. Donec nunc tellus, fermentum sed venenatis at, ultrices vitae dolor. Nullam in nulla eget neque consectetur ullamcorper sed id urna. Quisque elementum, lorem eget volutpat faucibus, nunc diam luctus dui, sit amet finibus tellus augue et augue. Vestibulum at ligula quis odio posuere ullamcorper nec vel purus. Quisque leo nisi, pulvinar venenatis tellus nec, luctus ornare arcu. Curabitur dignissim mollis nibh. Aliquam elementum justo sit amet ultricies varius. Morbi luctus felis dolor, non placerat arcu sollicitudin in. Duis in tempus urna, in blandit lacus. Praesent et fermentum dolor. In interdum diam libero, vitae pharetra arcu suscipit ut.";
	
	$scope.paragraph5 = "Sed sed ante lorem. Proin vulputate, purus sit amet tristique congue, nisi tortor pulvinar velit, ut condimentum diam risus at odio. Praesent erat ante, volutpat non suscipit a, mollis vel ligula. Vestibulum egestas odio nec lacus posuere euismod. Etiam neque dolor, lobortis sed lobortis vel, tempor non ante. In vel laoreet ex. Suspendisse id mollis est. Duis egestas ipsum diam, ac posuere justo dictum vel. Sed orci ipsum, eleifend quis felis ut, iaculis venenatis nunc. Pellentesque semper hendrerit fermentum.";
});
